### ISSUE TITLE
Cant run pocha on relative path starting with `test`

### ISSUE THREAD

**Issue by matutter** [rlgomes/pocha#16]
Pocha fails to import and run tests from a directory root of "test"
```
# Fails, no module named test
pocha test/test.py
```
Possible work around in `discovery.py:search`

```
for module in modules:
  module_path = os.path.dirname(module)
  sys_path = sys.path
  sys.path = ['.', module_path]
  try:
    ...
  finally:
    sys.path = sys_path
```

**Comment by rlgomes** [comment]
@matutter Are you trying to run from a `test` directory that doesn't have a __init__.py file in it ? ie its not a valid python module.

**Comment by matutter** [comment]
My bad, having any python file in the directory with the same name as the `.py` causes import errors. ie, `test/test.py` cannot be imported, even with an `__init__.py`.

**Comment by rlgomes** [comment]
@matutter I'll have a look this weekend and probably just use your suggestion, thanks!
